#-------------------------------
# General Site Settings
baseURL = "http://example.org/"
languageCode = "en-us"
title = "Akio"
googleAnalytics = "" # Add your identifier. For example UA-99631805-1.
paginate = 5


[params]
  logo = "" # You can add own logo. For example "/images/logo.png".
  description = "Creative Portfolio Theme for Hugo"
  color_scheme = "auto" # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


#-------------------------------
# Main Menu
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

  [[menu.main]]
    name = "Work"
    url = "/works/"
    weight = 3

  [[menu.main]]
    name = "Writing"
    url = "/posts/"
    weight = 4

  [[menu.main]]
    name = "Pages"
    weight = 5
    hasChildren = true

  [[menu.main]]
    parent = "Pages"
    name = "Contact"
    url = "/contact/"
    weight = 1

  [[menu.main]]
    parent = "Pages"
    name = "Elements"
    url = "/elements/"
    weight = 2


  #-------------------------------
  # Author Settings
  [params.author]
    author__name = "Reni Sharma"
    author__bio = "Hi there! I'm a qualified mental health therapist, here to help you feel your best. I'm passionate about helping others find balance and joy in their lives so that they can live life to the fullest. Let's work together to find the solutions you need to get back on the path to success!"
    author__avatar = "https://via.placeholder.com/400x400"

  # Social Links
  [[params.social]]
    icon = "ion-logo-twitter"
    name = "Twitter"
    link = "https://twitter.com"

  [[params.social]]
    icon = "ion-logo-facebook"
    name = "Facebook"
    link = "https://facebook.com"

  [[params.social]]
    icon = "ion-logo-instagram"
    name = "Instagram"
    link = "https://instagram.com"

  [[params.social]]
    icon = "ion-logo-pinterest"
    name = "Pinterest"
    link = "https://pinterest.com"

  [[params.social]]
    icon = "ion-logo-github"
    name = "Github"
    link = "https://github.com"

  [[params.social]]
    icon = "ion-logo-vimeo"
    name = "Vimeo"
    link = "https://vimeo.com"

  # Example of adding a new link to the footer:
  # [[params.social]]
  #   icon = "ion-logo-youtube"
  #   name = "Youtube"
  #   link = "https://youtube.com"

  # Other icons can be found at https://ionicons.com/v4/


  #-------------------------------
  # Hero Settings
  [params.hero]
    enable = true
    hero__title = "Hey everyone, I’m Reni Sharma"
    hero__description = "I'm a qualified mental health therapist, here to help you feel your best. I'm passionate about helping others find balance and joy in their lives so that they can live life to the fullest :)"
    hero__image = "https://via.placeholder.com/1200x800"


    #-------------------------------
    # Logos Settings
    [params.logos]
      enable = true
      logos__title = "I’ve worked with some great сompanies"

    [[params.logo_item]]
      name = "Google"
      link = "https://www.google.com/"
      image = "/images/google.svg"

    [[params.logo_item]]
      name = "Spotify"
      link = "https://www.spotify.com/"
      image = "/images/spotify.svg"

    [[params.logo_item]]
      name = "Pinterest"
      link = "https://www.pinterest.com/"
      image = "/images/pinterest.svg"

    [[params.logo_item]]
      name = "Netlify"
      link = "https://www.netlify.com/"
      image = "/images/netlify.svg"

    [[params.logo_item]]
      name = "Apple"
      link = "https://www.apple.com/"
      image = "/images/apple.svg"

    [[params.logo_item]]
      name = "Adobe"
      link = "https://www.adobe.com/"
      image = "/images/adobe.svg"


  #-------------------------------
  # Newsletter Settings
  [params.mailchimp]
    enable = true
    mailchimp__identifier = "frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3" # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
    mailchimp__input__text = "Your email address..."
    mailchimp__button__text = "Subscribe" # Add your button text


  #-------------------------------
  # Work Settings
  [params.work]
    enable = true
    work__title= "Projects"
    work__description= "Unlock your potential and reach your goals with my self-help workbooks and online courses!"


  #-------------------------------
  # Testimonials Section
  [params.testimonials]
    enable = true
    testimonial__title = "Clients"
    testimonial__description = ""

  [[params.testimonial_item]]
    name = "Hanna Septimus"
    image = "https://via.placeholder.com/400x400"
    designation = "Product Designer"
    link = "https://twitter.com/"
    content = "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"

  [[params.testimonial_item]]
    name = "Carla Rosser"
    image = "https://via.placeholder.com/400x400"
    designation = "Statistician"
    link = "https://facebook.com/"
    content = "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"

  [[params.testimonial_item]]
    name = "Maria Curtis"
    image = "https://via.placeholder.com/400x400"
    designation = "Team Lead"
    link = "https://twitter.com/"
    content = "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"

  [[params.testimonial_item]]
    name = "Carter Bergson"
    image = "https://via.placeholder.com/400x400"
    designation = "CEO, Founder"
    link = "https://facebook.com/"
    content = "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"

  [[params.testimonial_item]]
    name = "Jordyn Franci"
    image = "https://via.placeholder.com/400x400"
    designation = "Personal Trainer"
    link = "https://twitter.com/"
    content = "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"

  [[params.testimonial_item]]
    name = "Mira Carder"
    image = "https://via.placeholder.com/400x400"
    designation = "Data Scientist"
    link = "https://twitter.com/"
    content = "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"

  [[params.testimonial_item]]
    name = "Madelyn Herwitz"
    image = "https://via.placeholder.com/400x400"
    designation = "Frontend Engineer"
    link = "https://twitter.com/"
    content = "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"

  [[params.testimonial_item]]
    name = "Anika Schleifer"
    image = "https://via.placeholder.com/400x400"
    designation = "Fitness Director"
    link = "https://twitter.com/"
    content = "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"

  [[params.testimonial_item]]
    name = "Wilson Dorwart"
    image = "https://via.placeholder.com/400x400"
    designation = "Financial Manager"
    link = "https://twitter.com/"
    content = "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"


  #-------------------------------
  # Blog Section
  [params.blog]
    enable = true
    blog__title = "Writing"
    blog__description = ""


  #-------------------------------
  # Footer Settings
  [params.footer]
    footer__background__image = "https://via.placeholder.com/1920x1080"


  #-------------------------------
  # Contact Settings
  [params.contact]
    contact__email = "your@email.com" # Add your form_id

    # NOTE
    # Akio theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


  #-------------------------------
  # Comment Section (Disqus)
  [params.disqus]
    enable = true
    disqusShortname = "anvod-studio-test" # Add your shortname for Disqus Comment. For example anvod-studio-test


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[markup.highlight]
  codeFences = true
  guessSyntax = true
  noClasses = false